### ISSUE TITLE
As a moderator, I will be able to automatically delete messages with keywords chosen by me so that the chat can be moderated when moderators are away.

### ISSUE THREAD

**Issue by arjunshankkar** [ucsb-cs48-w20/5pm-discord#10]
- [x] the command is called with ?filter #channelname "list,of,keywords"

- [x] the command is disabled with ?endfilter #channelname

- [x] while the command is active, all messages sent in the channel are deleted if they contain any of the keywords

- [x] moderator messages won't be filtered (to avoid the filter being stuck on after poor keyword choice)

**Comment by theonlyt3** [comment]
Mentor approved ✅
