### ISSUE TITLE
As a moderator, I will be able to use a tempmute command so that I can prevent certain users from speaking for a specified time.

### ISSUE THREAD

**Issue by arjunshankkar** [ucsb-cs48-w20/5pm-discord#12]
- [x]  the command is called with ?tempmute @username (number of minutes)

- [x] if the user does not specify a number, the bot returns a error message specifying the proper format

- [x] the bot checks if the user who called the command has the correct permissions the command deletes the specified number of messages
--

**Comment by pkuang5** [comment]
- [ ] the command is called with ?mute  (number)

- [ ] if the user does not specify a number, the bot returns a error message specifying the proper format

- [ ] the bot checks if the user who called the command has the correct permissions the command deletes the specified number of messages
--

**Comment by theonlyt3** [comment]
Mentor approved ✅
