### ISSUE TITLE
As a user, I will be able to queue music from YouTube so that users can listen to music in their voice chat

### ISSUE THREAD

**Issue by Ulramok** [ucsb-cs48-w20/5pm-discord#18]
- [x] ?play [keyword] will return top ten results and will give the user the option to choose a song and queue it to the channel. 

- [x] have the option to add a youtube playlist into a queue

- [x] ?pause will pause the song being played

- [x] ?resume will resume the current song

- [ ] only allow for admin role or "DJ" role

- [ ] ?skip will skip the song

- [x] ?volume 1-10 will set the volume of voice channel

- [x] ?queue will display songs on the queue

**Comment by theonlyt3** [comment]
Mentor approved ✅ cool idea 👍
