### ISSUE TITLE
As a user, I will be able to self-assign roles so that the moderator does not need to give discord roles.

### ISSUE THREAD

**Issue by arjunshankkar** [ucsb-cs48-w20/5pm-discord#9]
- [x] The command can be called with ?assign "+/-role"

- [x] Checks that a valid input is provided and prints the correct syntax if not.

- [x] Checks that the provided role actually exists and prints the list of roles if not.

- [x] Changes the user's role and prints a public message that the user has done so.

- [x] Can both add and remove roles

**Comment by theonlyt3** [comment]
Mentor approved ✅
